/*
  Vantage AI token compiler.

  Reads tokens/color-tokens.json and writes tokens/design-tokens.css.
  The output is a Tailwind CSS v4 theme file, theme-aware utilities,
  and semantic role variables for the light and dark themes.

  Usage: node tokens/convert-tokens.js
*/
const fs = require('fs');
const path = require('path');

const jsonPath = path.join(__dirname, 'color-tokens.json');
const cssPath = path.join(__dirname, 'design-tokens.css');

if (!fs.existsSync(jsonPath)) {
  console.error(`Error: ${jsonPath} does not exist.`);
  process.exit(1);
}

const tokens = JSON.parse(fs.readFileSync(jsonPath, 'utf8'));
const primitives = tokens.primitives || {};
const errors = [];

const HEX = /^#([0-9a-fA-F]{6})$/;
for (const [name, value] of Object.entries(primitives)) {
  if (!HEX.test(value)) errors.push(`Primitive "${name}" must be a 6-digit hex value, got "${value}".`);
}

// Typography sizes get a default line height so `text-sm` alone matches the reference UI.
const DEFAULT_LINE_HEIGHTS = {
  'text-xs': '1.45',
  'text-sm': '1.45',
  'text-base': '1.45',
  'text-lg': '1.45',
  'text-xl': '1.2',
  'text-2xl': '1.2',
};

// Tokens that are not Tailwind theme namespaces live on :root instead of @theme.
const ROOT_ONLY = new Set(['duration-fast', 'duration-base']);

const line = (name, value, indent = '  ') => `${indent}--${name}: ${value};\n`;

let css = `/*
  THIS FILE IS AUTO-GENERATED BY tokens/convert-tokens.js.
  DO NOT EDIT DIRECTLY. Edit tokens/color-tokens.json and re-run:
    node tokens/convert-tokens.js
*/

/* ==========================================================================
   TAILWIND THEME (primitives + scales)
   Import this file after \`@import "tailwindcss";\` in app/globals.css.
   ========================================================================== */
@theme static {
  /* Remove Tailwind's default palette so only Vantage colors exist. */
  --color-*: initial;

  /* --- COLOR PRIMITIVES --- */
`;

for (const [name, value] of Object.entries(primitives)) {
  css += line(`color-${name}`, value.toUpperCase());
}

const nonColorCategories = ['typography', 'spacing', 'borderRadius', 'shadows', 'motion', 'layout'];
const rootOnly = [];

for (const category of nonColorCategories) {
  const group = tokens[category];
  if (!group) continue;
  css += `\n  /* --- ${category.toUpperCase()} --- */\n`;
  for (const [name, value] of Object.entries(group)) {
    if (ROOT_ONLY.has(name)) {
      rootOnly.push([name, value]);
      continue;
    }
    css += line(name, value);
    if (DEFAULT_LINE_HEIGHTS[name]) {
      css += line(`${name}--line-height`, DEFAULT_LINE_HEIGHTS[name]);
    }
  }
}

css += `}
`;

const light = (tokens.color && tokens.color.light) || {};
const dark = (tokens.color && tokens.color.dark) || {};
const utilities = tokens.utilities || {};

// Both themes must define exactly the same roles.
for (const role of Object.keys(light)) {
  if (!(role in dark)) errors.push(`Role "${role}" is missing from the dark theme.`);
}
for (const role of Object.keys(dark)) {
  if (!(role in light)) errors.push(`Role "${role}" is missing from the light theme.`);
}

function roleLines(theme, indent) {
  let out = '';
  for (const [role, primitiveName] of Object.entries(theme)) {
    if (!primitives[primitiveName]) {
      errors.push(`Role "${role}" references unknown primitive "${primitiveName}".`);
      continue;
    }
    out += line(role, `var(--color-${primitiveName})`, indent);
  }
  return out;
}

// Theme-aware Tailwind utilities (bg-surface, text-fg, border-line, ...).
css += `
/* ==========================================================================
   THEME-AWARE UTILITIES
   These resolve through the role variables below, so they switch with the
   theme. Use them in components for anything that changes between themes.
   ========================================================================== */
@theme inline {
`;
for (const [name, role] of Object.entries(utilities)) {
  if (!(role in light)) {
    errors.push(`Utility "${name}" references unknown role "${role}".`);
    continue;
  }
  css += line(`color-${name}`, `var(--${role})`);
}
css += `}

/* ==========================================================================
   SEMANTIC ROLES (light theme, default)
   ========================================================================== */
:root,
[data-theme="light"] {
`;
css += roleLines(light, '  ');

if (rootOnly.length) {
  css += `\n  /* --- MOTION DURATIONS --- */\n`;
  for (const [name, value] of rootOnly) css += line(name, value);
}

css += `}

/* ==========================================================================
   SEMANTIC ROLES (dark theme)
   Translated from the Vantage AI Figma file. Primary stays #3929CE.
   ========================================================================== */
[data-theme="dark"] {
${roleLines(dark, '  ')}}

/* Follow the system preference unless the user explicitly chose light. */
@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
${roleLines(dark, '    ')}  }
}
`;

if (errors.length) {
  console.error('Token validation failed:\n- ' + errors.join('\n- '));
  process.exit(1);
}

fs.writeFileSync(cssPath, css, 'utf8');
console.log(`Successfully generated ${cssPath}`);
